# 第5章 pandas入门

In [1]:
#pandas常用于数据清洗和分析工作，与数值计算的工具NumPy和SciPy,分析库
#statsmodels和scikit-learn,和数据可视化库matplotlib结合
#pandas采用了numpy编码风格。pandas专门处理表格和混杂数据设计的，而numpy
#更适合处理统一的数值数组数据

In [12]:
import pandas as pd
from pandas import Series,DataFrame

## 5.1 pandas的数据结构介绍

In [3]:
#pandas的两个数据结构：Series和DataFrame

### Series

In [13]:
#series由一组数据（numpy数据类型）以及一组与之相关的数据标签（索引）组成
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [14]:
#由于没有为数据制定索引，会自动创建一个0——N-1的整数型索引
#Series的values和index属性
obj.values

array([ 4,  7, -5,  3])

In [15]:
obj.index    #like range(4)

RangeIndex(start=0, stop=4, step=1)

In [16]:
#对各个数据点进行标记的索引
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [17]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [18]:
#可以通过索引获取Series中的单个或一组值
obj2['a']

-5

In [19]:
obj2['d']

4

In [20]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [21]:
#对Series进行numpy的运算或类似numpy运算，会保留索引值
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [22]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [23]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [24]:
#可以将Series看成一个定长的有序字典，它可以用在许多原本需要字典参数的函数中
'b' in obj2

True

In [25]:
'e' in obj2

False

In [26]:
#数据被存放在一个python字典中，可以通过这个字典直接创建Series
sdata = {'Ohio':35000,'Texas':71000,'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3     #注意虽然python字典是无序的，但是obj3是有序的

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
#传入排好序的字典的键以改变顺序
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
#在pandas中用NaN表示缺失（missing）或者NA值
#pandas中的isnull和notnull函数可以用来检测缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [30]:
#Series也有实例方法
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
#Series最重要的一个功能是，它会根据运算的索引标签自动对齐数据
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [29]:
#Series对象本身及其索引都有一个name属性,该属性与pandas其他的关键功能有关
obj4.name = 'population'    #人口
obj4.index.name = 'state'    #州
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [30]:
#Series可索引可以通过赋值的方式就地修改
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [31]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [86]:
# DataFrame
#DataFrame是一个表格型的数据结构，每一列可以是不同的数据类型，既有行索引
#也有列索引。DataFrame可以被看作是一个或多个二维块存放的
import pandas as pd
#传入等长的列表的字典建立DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [2]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [3]:
frame.head()   #提取DataFrame数据的前5行

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [5]:
#指定列序列，DataFrame会按指定序列排列
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [87]:
#如果传入的列找不到，会产生缺失值
#columns列索引 index行索引
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [88]:
frame2.columns    #列索引

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [89]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [90]:
#通过字典标记或属性的方式，可以将DataFrame的列获取为一个Series
#返回的Series拥有原DataFrame相同的索引，且name属性也被设置好了
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [91]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [92]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [93]:
#行也可以通过位置或者名称的方式进行获取
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [94]:
#列可以通''过赋值的方式修改
frame2['debt'] = 16.5

In [95]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [96]:
frame2['debt'] = np.arange(6.)  #将列表或数组赋值给某个列时，其长度必须与DataFrame长度匹配

In [97]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [98]:
#如果将一个Series赋值给DataFrame列，就会精确匹配DataFrame的索引
#没有匹配到的索引会成为NaN
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [99]:
#为不存在的列赋值，会创建出一个新列
frame2.state == 'Ohio'

one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool

In [100]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2
#不能用frame2.eastern创建新的列

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [101]:
#删除列
del frame2['eastern']

In [102]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [103]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [104]:
#注意通过索引方式返回的数据是源数据的视图，不是副本。
#因此对返回的Series所做的任何修改都会反映到源数据上
#通过Series的copy的方法可以指定复制列

In [105]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [106]:
pops = frame2['pop']
pops    #pops是一个Series

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
six      3.2
Name: pop, dtype: float64

In [112]:
#
#pops.iloc[:] = 1 
#pops['one':'six'] = 2
pops[:] = 3

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [113]:
pops

one      3.0
two      3.0
three    3.0
four     3.0
five     3.0
six      3.0
Name: pop, dtype: float64

In [114]:
frame2   #对源数据产生了影响

year   state  pop  debt
one    2000    Ohio  3.0   NaN
two    2001    Ohio  3.0  -1.2
three  2002    Ohio  3.0   NaN
four   2001  Nevada  3.0  -1.5
five   2002  Nevada  3.0  -1.7
six    2003  Nevada  3.0   NaN

In [115]:
pops_cp = frame2['pop'].copy()
pops_cp

one      3.0
two      3.0
three    3.0
four     3.0
five     3.0
six      3.0
Name: pop, dtype: float64

In [116]:
pops_cp.iloc[:] = 2

In [117]:
pops_cp

one      2.0
two      2.0
three    2.0
four     2.0
five     2.0
six      2.0
Name: pop, dtype: float64

In [118]:
frame2   #对源数据没有影响

year   state  pop  debt
one    2000    Ohio  3.0   NaN
two    2001    Ohio  3.0  -1.2
three  2002    Ohio  3.0   NaN
four   2001  Nevada  3.0  -1.5
five   2002  Nevada  3.0  -1.7
six    2003  Nevada  3.0   NaN

In [11]:
#传递嵌套字典创建DataFrame,pandas会将外层字典的键作为列，内层字典的键作为行索引
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
#内层字典的键会被合并，排序，最终形成最终的索引

In [12]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [13]:
#可以使用NumPy的方法对DataFrame进行转置
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [14]:
#传递嵌套字典也可以指定索引
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [15]:
#由Series组成的字典也可以创建DataFrame,相当于嵌套字典
frame3['Ohio'][:-1]

2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [16]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:-2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     NaN

In [17]:
#DataFrame的index和columns有name属性
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [18]:
#设置了index和columns的name属性，它们也会显示出来
frame3.index.name = 'year';frame3.columns.name = 'state'

In [19]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [137]:
frame3.values   #和Series一样，DataFrame.values属性返回是ndarray

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [139]:
frame3.values.dtype

dtype('float64')

In [144]:
#如果DataFrame中的数据类型不同，则values属性返回的ndarray的类型尽可能地包含所有类型
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [146]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 索引对象

In [2]:
import pandas as pd
#pandas的索引对象负责管理轴标签和其他元数据（例如轴名称）
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index

In [3]:
index

Index(['a', 'b', 'c'], dtype='object')

In [4]:
index[1:]

Index(['b', 'c'], dtype='object')

In [5]:
#index对象是不可变的，用户不能对其进行修改
index[1] = 'd'

TypeError: Index does not support mutable operations

In [7]:
#index对象不可变，使得index在多个数据结构间安全共享
#创建index对象
import numpy as np
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [8]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [9]:
obj2.index is labels    #同一个对象

True

In [20]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [21]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [22]:
'Ohio' in frame3.columns

True

In [23]:
2003 in frame3.index

False

In [24]:
#pandas的index可以包含重复的标签
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 基本功能

### 重要索引

In [25]:
#pandas对象的reindex方法会根据新索引进行重新排序，当某个索引不存在，就引入缺失值
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [26]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [27]:
#对于时间序列这样的数据，重新索引可能需要插值，method参数可以达到这一目的
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [28]:
obj3.reindex(range(6),method='ffill')   #ffill向前填充


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [32]:
#对于DataFrame对象，reindex可以修改行索引和列索引
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [33]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [34]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [35]:
states = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 丢弃指定轴上的项

In [40]:
#drop方法返回的是在一个指定轴上删除了指定值后的新对象
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [41]:
new_obj = obj.drop('c')

In [42]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [43]:
obj     #原对象并未改变

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [39]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [45]:
#对于DataFrame,drop方法可以删除任意轴上的索引值
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [46]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [50]:
data.drop(['Colorado','Ohio'])   #删除行

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [51]:
data     #data并未发生改变

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [52]:
data.drop('two',axis=1)  #axis='columns'

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [53]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [54]:
#drop方法会返回一个新的对象，对原对象没有影响，也可以就地修改，对原对象造成影响
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [55]:
obj.drop('c',inplace=True)

In [56]:
obj   #原对象发生了改变

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 索引、选取和过滤

In [4]:
#Series的索引类似于NumPy,只是Series的索引值不只是整数
import numpy as np
import pandas as pd
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [5]:
obj['b']    #类似字典的索引

1.0

In [6]:
obj[1]   #数字索引

1.0

In [9]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [10]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [11]:
obj[[1,3]]   #索引两个值

b    1.0
d    3.0
dtype: float64

In [12]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [13]:
#利用标签的切片运算与普通的python不同，其末端的包含的
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [14]:
#利用切片对Series的相应部分设置
obj['b':'c'] = 5

In [141]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [15]:
#对DataFrame进行索引
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [20]:
data['two']   #对列进行索引/  索引结果是1列数据，返回的是Series类型

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [21]:
data[['three','one']]    #对列进行索引，返回的是FrameData类型

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [22]:
data[:2]    #对行进行索引

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [146]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [147]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [148]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [150]:
data[:2]    #选取行，对行进行索引

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [152]:
data[2]  #报错，不能选取行

KeyError: 0

In [153]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [157]:
data[data<5] = 0   #小于5的位置改为0，其他不变

In [158]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 用loc和iloc进行行选取

In [23]:
#对于DataFrame的行选取，引入特殊的标签运算符loc和iloc
#loc轴便签 iloc整数标签 从DataFrame选择行和列的子集
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [25]:
data.loc['Colorado',['two','three']]   #标签行选取,索引后返回的数据类型是Series

two      5
three    6
Name: Colorado, dtype: int64

In [26]:
data.iloc[2,[3,0,1]]  #整数行选取

four    11
one      8
two      9
Name: Utah, dtype: int64

In [27]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [30]:
data.iloc[[1,2],[3,0,1]]   #返回的数据类型是DataFrame

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [31]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
#这两个索引函数也适用于一个标签或多个标签的切片
data.loc[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [35]:
data.three > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [ ]:
data.iloc[:,:3]   #不能写成data.iloc[[:],[:3]]

In [34]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### 整数索引

In [39]:
#pandas对象的整数索引与python内置的列表和元组的索引语法不同
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [41]:
ser[2]  #整数索引0，1，2

2.0

In [42]:
ser[-1]  #报错

KeyError: -1

In [43]:
#非整数索引
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [44]:
ser2[-1]   #对于非整数索引，这样不会报错#

2.0

In [45]:
#如果轴索引含有整数，数据选取总会使用标签，
#为了更准确，请使用loc(标签)（使用标签索引）或iloc（整数）（使用整数索引）
ser[:1]

0    0.0
dtype: float64

In [46]:
ser.loc[:1]  #标签索引是包含末尾值的

0    0.0
1    1.0
dtype: float64

In [47]:
ser.iloc[:1]  #整数索引的不含末尾值的

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [49]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [50]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [51]:
s1 + s2   #缺失值取NaN
#自动的数据对齐操作，在不重叠的索引处引入了NA值，缺失值会在算数运算过程中广播

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [53]:
#对于DataFrame,对齐操作为同时发生在行和列上
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [54]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [55]:
#两个DataFrame相加会返回一个新的DataFrame,其索引和列为原来那两个DataFrame的并集
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [57]:
#如果两个DataFrame没有共同的行或列标签，(注意这里是或)相加的话为全是NA
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[1,2]})

In [58]:
df1

A
0  1
1  2

In [59]:
df2

B
0  1
1  2

In [61]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### Arithmetic methods with fill values

In [62]:
#当对不同索引对象进行运算时，希望当一个对象中某个轴标签在另一个对象中
#找不到时填充一个特殊值（比如0）
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [64]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [65]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [66]:
df2.loc[1,'b'] = np.nan   #np.nan为NaN

In [67]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [68]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [69]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [70]:
df2.add(df1,fill_value=0)   #效果一样

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [71]:
1/df1
#每一个算数方法都有一个副本，以r开头，它会翻转参数

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [72]:
df1.rdiv(1)  #与上面的等价

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [73]:
#在对Series和DataFrame重新索引时，也可以指定一个填充值
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [74]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [76]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series

In [77]:
#计算某个二维数组与某行间的差
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [78]:
arr[0]

array([0., 1., 2., 3.])

In [79]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [80]:
#当我们从arr中减去arr[0],每一行都会执行这个操作，这叫广播（broadcasting）
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [81]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [82]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [83]:
#默认情况下，DataFrame和Series之间的算数运算会将Series的索引匹配到DataFrame的列,
#然后沿着行一直向下广播
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [85]:
#如果某个索引值在Dataframe的列或Series的索引中找不到，则参与运算
#的两个对象就会被重新索引以形成并集
series2 = pd.Series(range(3),index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [86]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [87]:
#如果你希望匹配行并且在列上广播，则必须使用算数运算方法(即对象的方法)
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [88]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [90]:
series3 - frame   #全是NaN

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [92]:
frame.sub(series3,axis='index')    #frame - series3 
#frame.sub(series3,axis=0)  #和上面效果一样

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [93]:
#numpy的ufuncs（元素级(数组方法）也可与操作pandas对象
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -1.261077  0.539831 -0.800460
Ohio    0.360506 -0.098456 -1.991805
Texas   0.275168  1.095702 -0.954138
Oregon  1.161660  0.050546 -0.988504

In [94]:
frame.abs() #DataFrame对象有abs方法

b         d         e
Utah    1.261077  0.539831  0.800460
Ohio    0.360506  0.098456  1.991805
Texas   0.275168  1.095702  0.954138
Oregon  1.161660  0.050546  0.988504

In [95]:
np.abs(frame)

b         d         e
Utah    1.261077  0.539831  0.800460
Ohio    0.360506  0.098456  1.991805
Texas   0.275168  1.095702  0.954138
Oregon  1.161660  0.050546  0.988504

In [97]:
#将函数应用到各行或各列所形成的一维数组上，DataFrame.apply 方法可以实现
f = lambda x : x.max() - x.min()
#x是一个series对象，series对象有max方法
frame.apply(f)  #默认是以列作为索引
#结果仍是一个series

b    2.422737
d    1.194158
e    1.191345
dtype: float64

In [98]:
frame.apply(f,axis='columns')   #以列作为索引

Utah      1.800908
Ohio      2.352311
Texas     2.049840
Oregon    2.150164
dtype: float64

In [100]:
#许多数据统计功能都被实现成了DataFrame方法，因此不需要用apply方法
#传递到apply的函数不是必须返回一个标量,还可以返回多个值组成的series
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.261077 -0.098456 -1.991805
max  1.161660  1.095702 -0.800460

In [101]:
#得到frame中各个浮点值的格式化字符串，可以使用applymap
#元素级别的函数
format = lambda x : '%.2f' % x    #浮点数保留2位
frame.applymap(format)

b      d      e
Utah    -1.26   0.54  -0.80
Ohio     0.36  -0.10  -1.99
Texas    0.28   1.10  -0.95
Oregon   1.16   0.05  -0.99

In [102]:
#之所以叫applymap
#series有一个用于元素级函数的map方法
frame['e'].map(format)

Utah      -0.80
Ohio      -1.99
Texas     -0.95
Oregon    -0.99
Name: e, dtype: object

### Sorting and Ranking

In [104]:
#按行或者列进行排序，可以使用sort_index方法,它返回一个已排序的新对象，不会对原数据改变
obj = pd.Series(range(4),index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [105]:
obj.sort_index()   #因为是series，只能对一个轴的索引进行排序

a    1
b    2
c    3
d    0
dtype: int64

In [110]:
#对DataFrame,index_sort可以对任意一个轴上的索引进行排序
#注意是对轴的索引进行排序，不是对值进行排序
frame = pd.DataFrame(np.random.randn(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d         a         b         c
three -0.269744 -1.032509  0.946315 -1.252950
one   -0.083371 -0.040609 -1.608948 -1.309702

In [111]:
frame.sort_index()   #默认axis=0

d         a         b         c
one   -0.083371 -0.040609 -1.608948 -1.309702
three -0.269744 -1.032509  0.946315 -1.252950

In [112]:
frame.sort_index(axis=1)

a         b         c         d
three -1.032509  0.946315 -1.252950 -0.269744
one   -0.040609 -1.608948 -1.309702 -0.083371

In [113]:
frame.sort_index(axis=1,ascending=False)

d         c         b         a
three -0.269744 -1.252950  0.946315 -1.032509
one   -0.083371 -1.309702 -1.608948 -0.040609

In [114]:
#按值对Series进行排序，可以用sort_values方法
obj = pd.Series([4,7,-3,2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [115]:
obj.sort_values()    # series只有一个轴

2   -3
3    2
0    4
1    7
dtype: int64

In [116]:
#对series排序，对任何缺失值，对会被放在末尾
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [117]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [119]:
#对DataFrame进行排序时，希望根据一个或多个列中的值进行排序
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [120]:
frame.sort_values(by='b')   #根据‘b’列进行排序，其他被动跟着

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [122]:
frame.sort_values(by='a')

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [121]:
frame.sort_values(by=['a','b'])   #先满足‘a’的排序，在‘a’的基础上，再对‘b’列排序（只有a列的相同值排序）

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [124]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [125]:
obj.rank()   #排位次 有两个位次一样的，取平均
#series.rank(method='average')

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [126]:
obj.rank(method='first')  #条目0与条目2被设置成了6，7，因为条目0在条目2的前面

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [128]:
obj.rank(method='max')   #相同的排名取大的排名

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [129]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [130]:
#DataFrame也有rank方法
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [132]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 带有重复标签的轴索引

In [133]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [134]:
#is_unique属性可以告诉你值是否唯一
obj.index

Index(['a', 'a', 'b', 'b', 'c'], dtype='object')

In [135]:
obj.index.is_unique

False

In [136]:
#如果某个索引对应多个值，会返回一个Series,而不是标量
obj['a']

a    0
a    1
dtype: int64

In [137]:
obj['c']

4

In [138]:
#dataframe重复标签的索引
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -0.434076  0.270586  1.288981
a  1.407200 -0.948919 -1.000728
b  0.272993 -0.371234  1.429329
b  0.429201 -0.760873  0.292384

In [139]:
df.loc['b']

0         1         2
b  0.272993 -0.371234  1.429329
b  0.429201 -0.760873  0.292384

## Summarizing and Computing Descriptive Statistics

In [142]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [143]:
df.sum()   #默认axis=0

one    9.25
two   -5.80
dtype: float64

In [146]:
df.sum(axis=1)   #NaN会被自动排除，除非整个切片都是NaN

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [147]:
#NaN会被自动排除，除非整个切片都是NaN
#skipna可以禁用该功能
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [149]:
df.idxmin()  #返回最小值的索引

one    d
two    b
dtype: object

In [150]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [151]:
df.describe()   #对于数值型数据，一次性产生多个汇总统计量

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [152]:
#对于非数值型数据，describe会产生另外一种汇总统计
obj = pd.Series(['a','a','b','c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [153]:
import pandas_datareader.data as web

all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [155]:
returns = price.ptc_change()

AttributeError: 'DataFrame' object has no attribute 'ptc_change'

In [157]:
returns.tail()

NameError: name 'returns' is not defined

In [ ]:
#Series的corr方法用于计算两个Series中重叠的，非NA的，索引对齐的值的相关洗漱
returns['MSFT'].corr(returns['IBM'])
returns['MSFT'].cov(returns['IBM'])
#returns的MSFT属性
returns.MSFT.corr(returns.IBM)
#以dataframe的形式返回完整的相关系数或相关协方差矩阵
returns.corr()
returns.cov() 
#dataframe的corrwith方法可以计算其列或行跟另一个series或dataframe之间的相关系数
returns.corrwith(returns.IBM)
returns.corrwith(volume)

### 唯一值，值计数，成员资格

In [175]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [176]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [177]:
#获得series中的唯一数组
uniques = obj.unique()

In [178]:
uniques   #返回的是ndarray类型，返回结果并没有排序

array(['c', 'a', 'd', 'b'], dtype=object)

In [180]:
#value_count用于计算一个series中各个值出现的频率
obj.value_counts()   #结果按降序排列

a    3
c    3
b    2
d    1
dtype: int64

In [181]:
#value_counts还是一个顶级pandas方法，可以用于任何数组或序列#
pd.value_counts(obj.values,sort=False)

b    2
c    3
d    1
a    3
dtype: int64

In [182]:
#isin用于判断矢量化集合的成员资格,可以用来过滤series或dataframe列中数据的子集
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [183]:
mask = obj.isin(['b','c'])

In [184]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [185]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [187]:
#pd.Index().get_indexer()返回索引数组
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

In [190]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [191]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [204]:
pd.value_counts(data)    #value_counts传入的参数是dataframe会报错   
data.value_counts()   #报错

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

In [197]:
result = data.apply(pd.value_counts)

In [198]:
result
#data一共有1，2，3，4，5这些unique值,构成了行标签。比如3这个数在Qu1中有2个

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [205]:
result.fillna(0)  #将NA填0

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0