# Data Cleaning and Preparation

## 7.1 Handling Missing Data

In [1]:
#pandas对象的所有描述性统计量默认都不包括缺失数据
#pandas使用浮点数NaN(not a number)表示缺失数据

In [13]:
import numpy as np
import pandas as pd
string_data = pd.Series(['aardvark', 'artichoke',np.nan, 'avocado'])

In [14]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [15]:
string_data.isnull()   #用isnull检测NaN,也可以检测None,但NULL不是python的内置关键值

0    False
1    False
2     True
3    False
dtype: bool

In [16]:
#python内置的None值在pandas中也可以当作NaN
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 过滤缺失数据

In [19]:
#过滤缺失值，可以通过pandas.isnull得到布尔索引，然后在索引过滤掉NaN
#也可以用pandas.dropna
from numpy import nan as NA

In [20]:
data = pd.Series([1,NA,3.5,NA,7])

In [21]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [22]:
data.dropna()  #返回一个新对象

0    1.0
2    3.5
4    7.0
dtype: float64

In [23]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [24]:
data.notnull()   #与pandas.isnull相反

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [25]:
data[data.notnull()]  #效果与data.dropna() 一样

0    1.0
2    3.5
4    7.0
dtype: float64

In [26]:
#对于dataframe对象，dropna()默认丢弃任何含有缺失值的行
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])

In [27]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [28]:
cleaned = data.dropna()   #返回一个新对象

In [31]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [32]:
cleaned  #只要一行中有NA就会丢弃

0    1    2
0  1.0  6.5  3.0

In [33]:
#对dropna()传入参数how='all'，则只丢弃全部为NA的那些行
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [35]:
#丢弃列，只需要传入参数axis=1
data[4] = NA

In [36]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [37]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [38]:
df = pd.DataFrame(np.random.randn(7,3))

In [39]:
df

0         1         2
0 -0.810486  0.470835  0.897504
1 -0.005755  1.495745  0.524133
2  1.077162  1.178293  0.775936
3 -0.429914  2.562880 -1.964051
4 -1.130045  0.492024 -0.944027
5 -0.230686  0.184458  0.091506
6 -0.760567  0.362374 -0.659326

In [40]:
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA

In [41]:
df

0         1         2
0 -0.810486       NaN       NaN
1 -0.005755       NaN       NaN
2  1.077162       NaN  0.775936
3 -0.429914       NaN -1.964051
4 -1.130045  0.492024 -0.944027
5 -0.230686  0.184458  0.091506
6 -0.760567  0.362374 -0.659326

In [42]:
df.dropna()

0         1         2
4 -1.130045  0.492024 -0.944027
5 -0.230686  0.184458  0.091506
6 -0.760567  0.362374 -0.659326

In [43]:
#thresh=n 保留至少有n个非NaN的行
df.dropna(thresh=2)  #第0，1行只有1个非NaN数据，所以删除

0         1         2
2  1.077162       NaN  0.775936
3 -0.429914       NaN -1.964051
4 -1.130045  0.492024 -0.944027
5 -0.230686  0.184458  0.091506
6 -0.760567  0.362374 -0.659326

### Filling In Missing Data

In [44]:
#通过fillna方法填补NaN值
df

0         1         2
0 -0.810486       NaN       NaN
1 -0.005755       NaN       NaN
2  1.077162       NaN  0.775936
3 -0.429914       NaN -1.964051
4 -1.130045  0.492024 -0.944027
5 -0.230686  0.184458  0.091506
6 -0.760567  0.362374 -0.659326

In [45]:
df.fillna(0)   #所有的NaN值都填充0,生成以个新的对象

0         1         2
0 -0.810486  0.000000  0.000000
1 -0.005755  0.000000  0.000000
2  1.077162  0.000000  0.775936
3 -0.429914  0.000000 -1.964051
4 -1.130045  0.492024 -0.944027
5 -0.230686  0.184458  0.091506
6 -0.760567  0.362374 -0.659326

In [48]:
#若是通过一个字典调用fillna,就可以实现对不同列填充不同的值
df.fillna({1:0,2:1})   #对columns=1,填充0；对columns=2，填充1

0         1         2
0 -0.810486  0.000000  1.000000
1 -0.005755  0.000000  1.000000
2  1.077162  0.000000  0.775936
3 -0.429914  0.000000 -1.964051
4 -1.130045  0.492024 -0.944027
5 -0.230686  0.184458  0.091506
6 -0.760567  0.362374 -0.659326

In [49]:
#fillna默认返回新对象，但也可以对原对象就地修改
_ = df.fillna(0,inplace=True)

In [50]:
df

0         1         2
0 -0.810486  0.000000  0.000000
1 -0.005755  0.000000  0.000000
2  1.077162  0.000000  0.775936
3 -0.429914  0.000000 -1.964051
4 -1.130045  0.492024 -0.944027
5 -0.230686  0.184458  0.091506
6 -0.760567  0.362374 -0.659326

In [52]:
df = pd.DataFrame(np.random.randn(6,3))
df

0         1         2
0 -1.489787 -0.063011 -1.271185
1  1.433114  0.117672  0.571795
2  0.403217  0.034212 -0.151929
3  1.712899  2.304622  1.489136
4  1.011733  0.300445 -2.003349
5 -0.440247  1.858212 -0.895750

In [53]:
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA   #切片是对源数据的修改

In [54]:
df

0         1         2
0 -1.489787 -0.063011 -1.271185
1  1.433114  0.117672  0.571795
2  0.403217       NaN -0.151929
3  1.712899       NaN  1.489136
4  1.011733       NaN       NaN
5 -0.440247       NaN       NaN

In [55]:
df.fillna(method='ffill')  #按列的顺序向前填充

0         1         2
0 -1.489787 -0.063011 -1.271185
1  1.433114  0.117672  0.571795
2  0.403217  0.117672 -0.151929
3  1.712899  0.117672  1.489136
4  1.011733  0.117672  1.489136
5 -0.440247  0.117672  1.489136

In [58]:
df.fillna(method='ffill',axis=1)  #按行的顺序向前填充

0         1         2
0 -1.489787 -0.063011 -1.271185
1  1.433114  0.117672  0.571795
2  0.403217  0.403217 -0.151929
3  1.712899  1.712899  1.489136
4  1.011733  1.011733  1.011733
5 -0.440247 -0.440247 -0.440247

In [59]:
df.fillna(method='ffill',limit=2)  #最多填充2个

0         1         2
0 -1.489787 -0.063011 -1.271185
1  1.433114  0.117672  0.571795
2  0.403217  0.117672 -0.151929
3  1.712899  0.117672  1.489136
4  1.011733       NaN  1.489136
5 -0.440247       NaN  1.489136

In [60]:
#只要有些创新，可以利用fillna实现许多别的功能，比如说传入series的平均值或中位数
data = pd.Series([1.,NA,3.5,NA,7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [61]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [63]:
data.mean()  #pandas.mean()会自动过滤掉NaN值

3.8333333333333335

## 7.2 数据转换

### 移除重复数据

In [64]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [65]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [67]:
#dataframe的duplicated方法返回一个布尔型series，表示各行是否重复
#若有重复，则第一个重复行表示False,第二个重复行才是True
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [68]:
#drop_duplicateds方法会丢弃重复的行
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [70]:
data[-data.duplicated()]  #效果与data.drop.duplicates()一样

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [71]:
#df.drop_duplicates和df.duplicated()默认会判断全部列
#也可以指定部分列进行重复项判断
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [72]:
data.drop_duplicates(['k1'])  #指定k1列是否有重复

k1  k2  v1
0  one   1   0
1  two   1   1

In [73]:
#duplicated和drop_duplicates默认保留第一个出现的值组合
#传入keep='last'则保留最后一个
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [74]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [75]:
#想要添加一列表示该肉类食物涞源的动物类型
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [80]:
#series的map方法可以接受一个函数或含有映射关系的字典型对象
lowercased = data['food'].str.lower()  #series.str.lower方法将各个值转换为小写

In [81]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [82]:
#通过映射型字典赋值
data['animal'] = lowercased.map(meat_to_animal)

In [83]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [85]:
#通过函数来赋值
#lambda x 中的x 表示food列中的各个值
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 替换值

In [87]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [89]:
#这里-999这个值可能是表示缺失数据的标记值，现要将其替换成NA值
data.replace(-999,np.nan)  #产生一个新的series

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [90]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [91]:
#多个值替换成一个值
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [92]:
#多个值替换成多个值
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [93]:
#replace的参数也可以是字典
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [95]:
#注意series.replace与series.str.replace方法不同，后者是字符串的元素级替换

### 重命名轴索引

In [96]:
#series的轴标签也可以痛殴函数或映射进行转换，从而得到一个新的不同标签的对象
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [97]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [98]:
#和series一样,轴索引也有map方法
transform = lambda x: x[:4].upper()
transform

<function __main__.<lambda>(x)>

In [99]:
data.index.map(transform)  #得到一个新的对象

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [101]:
data  #并未发生改变

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [102]:
#赋值,对原数据发生了修改
data.index = data.index.map(transform)

In [103]:
data  # data发生了变化

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [105]:
#dataframe.rename()可以对index和columns修改
data.rename(index=str.title,columns=str.upper)  #生成以个新的对象
#title 首字母大写 upper 全部大写

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [106]:
data  #源对象没有发生改变

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [107]:
#rename()可传入字典参数
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [108]:
data   #源数据并未改变

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [109]:
#传入参数inplace就地修改，不生成新的对象
data.rename(index={'OHIO':'INDIANA'},inplace=True) 

In [110]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### Discretization and Binning

In [120]:
#为了便于分析，连续型数据常常被离散化或拆成“面元”（bin）
#假设有一组人员数据，希望将他们划分为不同的年龄组
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32,18,25,100]

In [121]:
#接下来，将这些数据划分为18-25，25-35，35-60，60-100的4个面元，可以是使用pandas.cut方法
bins = [18,25,35,60,100]   #(18,25] (25,35]
cats = pd.cut(ages,bins)

In [122]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (35.0, 60.0], (25.0, 35.0], NaN, (18.0, 25.0], (60.0, 100.0]]
Length: 15
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [123]:
#pandas返回的是一个特殊的Categorical对象，可以将其看做一组表示面元名称的字符串
#它的底层含有一个表示不同分类名称的类型数组，以及一个codes属性中的年龄数据的标签
cats.codes   #NaN用-1表示

array([ 0,  0,  0,  1,  0,  0,  2,  1,  3,  2,  2,  1, -1,  0,  3],
      dtype=int8)

In [124]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [125]:
pd.value_counts(cats)  #返回一个series

(18, 25]     6
(35, 60]     3
(25, 35]     3
(60, 100]    2
dtype: int64

In [126]:
#默认( ],哪边是闭端可以通过right=False来修改
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [36.0, 61.0), [26.0, 36.0), [18.0, 26.0), [18.0, 26.0), NaN]
Length: 15
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [127]:
#可以传递一个列表或数组到labels，设置面元名称
group_names = ['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., MiddleAged, YoungAdult, NaN, Youth, Senior]
Length: 15
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [128]:
#向cut传入的参数不是面元的边界，而是面元的数量，则会根据最大最小值计算等长面元
data = np.random.rand(20)
data

array([0.2235084 , 0.18988007, 0.89644223, 0.79644373, 0.22728949,
       0.48598068, 0.97008575, 0.57584695, 0.26062408, 0.01465974,
       0.70054092, 0.82067791, 0.98393089, 0.04993122, 0.81728889,
       0.18298592, 0.902529  , 0.08175202, 0.28600161, 0.6640834 ])

In [129]:
pd.cut(data,4,precision=2)    #限定小数只有2位

[(0.014, 0.26], (0.014, 0.26], (0.74, 0.98], (0.74, 0.98], (0.014, 0.26], ..., (0.014, 0.26], (0.74, 0.98], (0.014, 0.26], (0.26, 0.5], (0.5, 0.74]]
Length: 20
Categories (4, interval[float64]): [(0.014, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.98]]

In [130]:
#qcut可以根据样本的分位数进行面元划分
#cut函数可能无法使各个面元含有相同的数据量，而qcut可以
data = np.random.randn(1000)
cats = pd.qcut(data,4)  #cut into quartile

In [131]:
cats

[(0.0588, 0.722], (0.0588, 0.722], (0.0588, 0.722], (-0.6, 0.0588], (0.0588, 0.722], ..., (0.722, 2.74], (-3.177, -0.6], (-3.177, -0.6], (-3.177, -0.6], (-3.177, -0.6]]
Length: 1000
Categories (4, interval[float64]): [(-3.177, -0.6] < (-0.6, 0.0588] < (0.0588, 0.722] < (0.722, 2.74]]

In [132]:
cats.value_counts()

(-3.177, -0.6]     250
(-0.6, 0.0588]     250
(0.0588, 0.722]    250
(0.722, 2.74]      250
dtype: int64

In [134]:
#qcut可以传入自定的分位数（0到1之间的值，包含端点）
cats = pd.qcut(data,[0,0.1,0.5,0.9,1.])

In [135]:
cats.value_counts()

(-3.177, -1.172]    100
(-1.172, 0.0588]    400
(0.0588, 1.3]       400
(1.3, 2.74]         100
dtype: int64

### Detecting and Filtering Outliers

In [136]:
#过滤或变换异常值(outlier)，很大程度上运用数组运算
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()   #对每一列describe

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.059160    -0.043092     0.003034    -0.050469
std       0.966490     0.987472     1.026585     1.036539
min      -3.616382    -3.063462    -3.719557    -3.449287
25%      -0.689086    -0.691268    -0.681841    -0.734187
50%      -0.077882    -0.066990     0.021547    -0.058061
75%       0.584726     0.597610     0.696289     0.623105
max       3.145311     3.462391     2.760016     3.092929

In [137]:
#找出第2列绝对值大小超过3的值
col = data[2]

In [139]:
col[np.abs(col) > 3]

211   -3.614046
222   -3.226948
571   -3.719557
868   -3.154877
Name: 2, dtype: float64

In [148]:
#选出全部含有超过3或-3值的行
#(np.abs(data) > 3).any(axis=1)
data[(np.abs(data) > 3).any(1)]

0         1         2         3
30   1.267319 -0.130925  0.789567  3.026836
142 -1.093341 -0.810668  0.388066 -3.080007
189 -0.008657  3.370465  0.355296  0.711503
211  0.203763 -0.273264 -3.614046 -0.435736
222 -1.830518 -2.164094 -3.226948 -1.618062
238 -0.951990  3.462391 -0.181205 -1.066843
337  1.662007 -0.169710  1.544385 -3.327623
372 -0.391330  1.240267  0.750936  3.092929
445 -1.496724  1.199154  1.763625  3.022082
457  1.661079  3.092674 -0.020796 -0.486338
497 -0.593279  0.943542 -0.550610 -3.258156
503 -3.155178 -0.868889 -2.118771 -0.636498
571  2.105697 -1.494239 -3.719557 -1.850110
573 -3.616382  1.090611 -0.805387 -0.319089
723 -0.349119 -3.063462  0.382340  0.353737
772  1.882815  0.589922 -1.126439 -3.449287
839  3.145311 -0.010990  0.475023  1.163426
868  1.181410  0.885178 -3.154877  0.657238
994 -3.073759  0.009917  1.308204 -2.450446

In [152]:
#将绝对值大于3的值限制在-3到3之间
data[np.abs(data)>3] = np.sign(data) * 3
#sign大于0则返回1，小于0则返回-1

In [153]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.058460    -0.043954     0.004749    -0.049496
std       0.963226     0.984237     1.021073     1.032748
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.689086    -0.691268    -0.681841    -0.734187
50%      -0.077882    -0.066990     0.021547    -0.058061
75%       0.584726     0.597610     0.696289     0.623105
max       3.000000     3.000000     2.760016     3.000000

In [154]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0
2 -1.0 -1.0  1.0 -1.0
3  1.0  1.0 -1.0  1.0
4  1.0 -1.0 -1.0 -1.0

### Permutation and Random Sampling

In [187]:
#numpy.random.permutation函数可以实现对series和dataframe的列的排序工作
#（permuting,随机重排序）
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [196]:
#如果permutation()传入一个整数，则会返回洗牌后的arange
sampler = np.random.permutation(5)   #对5行进行重新排序
#sampler = np.random.permutation(4)  #只对前面4行进行重新排序

In [197]:
sampler

array([2, 1, 4, 0, 3])

In [198]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [199]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
1   4   5   6   7
4  16  17  18  19
0   0   1   2   3
3  12  13  14  15

In [201]:
df.sample(n=3)  #随机抽样选取3行

0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7

In [203]:
choices = pd.Series([5,7,-1,6,4])
#允许重复选择来选取样本
draws = choices.sample(n=10,replace=True)

In [204]:
draws

4    4
3    6
2   -1
0    5
4    4
0    5
2   -1
3    6
0    5
2   -1
dtype: int64

In [164]:
array = np.arange(10)
array_per = np.random.permutation(array)

In [165]:
array   #源对象不改变

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
array_per  #生成一个新的对象

array([9, 0, 6, 5, 2, 8, 1, 7, 4, 3])

In [169]:
array_mul = np.arange(15).reshape((5,3))
array_mul

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [178]:
#对于多维的array只对第0维进行洗牌，即只有行与行发生变化
np.random.permutation(array_mul)  

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [12, 13, 14],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [182]:
a = np.random.shuffle(array)   #对源对象进行洗牌,无返回值

In [185]:
a == None

True

In [186]:
array

array([4, 0, 2, 6, 7, 9, 5, 3, 1, 8])

### Computing Indicator/Dummy Variables

In [206]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [207]:
#如果dataframe的某一列中含有k个不同的值，可以派生出一个k列的dataframe
#其值全是0或1
pd.get_dummies(df['key'])
#因为df的第0行是b,所以结果的第0行1在b的位置上

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [208]:
#想给指标dataframe的列加上一个前缀，以便能够跟其他数据进行合并
dummies = pd.get_dummies(df['key'],prefix='key')  #prefix前缀

In [209]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [213]:
df_with_dummy = df[['data1']].join(dummies)
#注意这里‘data1’一定要两个[[]]

In [214]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [215]:
#注意这里‘data1’一定要两个[[]]

df['data1']  #返回series，series没有join方法

0    0
1    1
2    2
3    3
4    4
5    5
Name: data1, dtype: int64

In [216]:
df[['data1']]   #返回dataframe类型，只有dataframe类型才有,join方法

data1
0      0
1      1
2      2
3      3
4      4
5      5

In [219]:
#如果dataframe中的某行属于多个分类，则有点复杂
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames)
movies[:10]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: read_table is deprecated, use read_csv instead.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [231]:
#为每个genre添加指标变量，先从数据集中抽取不同的genre值
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))    #注意extend和append的区别 

In [278]:
#all_genres

In [237]:
genres = pd.unique(all_genres)

In [238]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [245]:
#构建指标dataframe的方法之一是从一个全零的dataframe开始
#len(movies)=行数
zero_matrix = np.zeros((len(movies), len(genres)))  
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [250]:
dummies = pd.DataFrame(zero_matrix,columns=genres)

In [253]:
#迭代每一部电影，并将dummies各行的条目设为1
gen = movies.genres[0]

In [254]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [256]:
dummies.columns.get_indexer(gen.split('|'))  #获得dummies的columns的标号

array([0, 1, 2])

In [258]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1

In [277]:
dummies

In [262]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [268]:
movies_windic.head()

movie_id                               title                        genres  \
0         1                    Toy Story (1995)   Animation|Children's|Comedy   
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2         3             Grumpier Old Men (1995)                Comedy|Romance   
3         4            Waiting to Exhale (1995)                  Comedy|Drama   
4         5  Father of the Bride Part II (1995)                        Comedy   

   Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Adventure  \
0              1.0               1.0           1.0              0.0   
1              0.0               1.0           0.0              1.0   
2              0.0               0.0           1.0              0.0   
3              0.0               0.0           1.0              0.0   
4              0.0               0.0           1.0              0.0   

   Genre_Fantasy  Genre_Romance  Genre_Drama  ...  Genre_Crime  \
0            0.0            0.0          0.0  ...          0.0   
1            1.0            0.0          0.0  ...          0.0   
2            0.0            1.0          0.0  ...          0.0   
3            0.0            0.0          1.0  ...          0.0   
4            0.0            0.0          0.0  ...          0.0   

   Genre_Thriller  Genre_Horror  Genre_Sci-Fi  Genre_Documentary  Genre_War  \
0             0.0           0.0           0.0                0.0        0.0   
1             0.0           0.0           0.0                0.0        0.0   
2             0.0           0.0           0.0                0.0        0.0   
3             0.0           0.0           0.0                0.0        0.0   
4             0.0           0.0           0.0                0.0        0.0   

   Genre_Musical  Genre_Mystery  Genre_Film-Noir  Genre_Western  
0            0.0            0.0              0.0            0.0  
1            0.0            0.0              0.0            0.0  
2            0.0            0.0              0.0            0.0  
3            0.0            0.0              0.0            0.0  
4            0.0            0.0              0.0            0.0  

[5 rows x 21 columns]

In [269]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [270]:
np.random.seed(12345)   #使用seed使例子具有确定性

In [271]:
values = np.random.rand(10)

In [272]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [273]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [279]:
pd.cut(values,bins)

[(0.8, 1.0], (0.2, 0.4], (0.0, 0.2], (0.2, 0.4], (0.4, 0.6], (0.4, 0.6], (0.8, 1.0], (0.6, 0.8], (0.6, 0.8], (0.6, 0.8]]
Categories (5, interval[float64]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [280]:
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## String Manipulation

### 字符串对象方法

In [281]:
#以逗号分割的字符串可以用split拆分
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [285]:
#strip()用于去除空白符
pieces = [x.strip() for x in val.split(',')]

In [286]:
pieces

['a', 'b', 'guido']

In [287]:
first,second,third = pieces

In [288]:
first + "::" + second + "::" + third

'a::b::guido'

In [289]:
"::".join(pieces)

'a::b::guido'

In [292]:
#检测字字符串
'guido' in val

True

In [297]:
val.index(',')   # ,的第一个索引位置,若找不到，则报错

1

In [294]:
val.find(':')  #找不到字符串是返回-1，而不是报错

-1

In [298]:
val.count(',')  #返回指定字符串出现的次数

2

In [299]:
#str.replace()用于将指定模式替换成另一个模式，通过传入空字符串，常用于删除
val.replace(',','::')    #生成一个新对象

'a::b:: guido'

In [300]:
val

'a,b, guido'

In [301]:
val.replace(',','')

'ab guido'

### 正则表达式

In [302]:
import re

In [303]:
#想要拆分一个字符串，分隔符为数量不定的一组空白符（\t,\n,空格等）
text = 'foo   bar\t baz \tqux'
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [304]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [305]:
regex.findall(text)

['   ', '\t ', ' \t']

In [306]:
#search()返回第一个匹配项，match()只匹配字符串的首部
text = """Dave dave@google.com
Steve steve@gamail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [313]:
pattern = '[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
#re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern,flags=re.IGNORECASE)

In [314]:
regex.findall(text)

['dave@google.com', 'steve@gamail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [327]:
mm = 'c:\\ab'   #字符串转义\\ 成为\

In [329]:
print(mm)

c:\ab


In [330]:
mn = r'c:\\ab'  #r的作用的防止转义,使用raw string
print(mn)

c:\\ab


In [332]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
print(pattern)

[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}


In [333]:
m = regex.search(text)

In [334]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [335]:
m.start()

5

In [336]:
m.end()

20

In [337]:
text[m.start():m.end()]

'dave@google.com'

In [338]:
print(regex.match(text))

None


In [340]:
#sub方法可以将匹配到模式替换成指定的字符串
print(regex.sub('REDACTED',text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [341]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [342]:
m = regex.match('wesm@bright.net')

In [343]:
m.groups()

('wesm', 'bright', 'net')

In [345]:
m.group(1)

'wesm'

In [346]:
#带有分组功能的模式，findall会返回一个元组列表
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gamail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [350]:
#sub还能通过诸如\1,\2之类的特殊符号访问各匹配项中的分组
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3',text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gamail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### Vectorized String Functions in pandas

In [369]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com','Wes': np.nan}

In [370]:
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [371]:
data = pd.Series(data)

In [372]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [373]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [375]:
#data.map(lambda x: x.title())   #报错 ，float object没有title(),因为NaN

In [376]:
#series有一些剋跳过nan值的面向数组的方法，进行字符串操作，通过series的str属性即可访问这些方法
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [380]:
data.str.title()

Dave     Dave@Google.Com
Steve    Steve@Gmail.Com
Rob        Rob@Gmail.Com
Wes                  NaN
dtype: object

In [378]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [379]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [381]:
#有两个办法可以实现矢量化的元素获取，要么使用str.get,
#要么在str属性上使用索引
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [389]:
matches.str

In [391]:
matches.str.get(1)   #bool对象没有get方法

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [383]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [384]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [408]:
import pandas as pd
import numpy as np
s = pd.Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h'])
s

0    a_b_c
1    c_d_e
2      NaN
3    f_g_h
dtype: object

In [396]:
s.str.split('_')

0    [a, b, c]
1    [c, d, e]
2          NaN
3    [f, g, h]
dtype: object

In [405]:
s.str.split('_',1)

0    [a, b_c]
1    [c, d_e]
2         NaN
3    [f, g_h]
dtype: object

In [406]:
s.str.get(0)

0      a
1      c
2    NaN
3      f
dtype: object

In [407]:
s.str.get(1)

0      _
1      _
2    NaN
3      _
dtype: object

In [409]:
s.str[0]

0      a
1      c
2    NaN
3      f
dtype: object