# 基础篇

## 理解NumPy

In [ ]:
## 创建一维数组

In [10]:
import numpy as np
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [11]:
print(my_array)

[1 2 3 4 5]


In [12]:
print(my_array.shape)

(5,)


In [13]:
print(my_array[0])
print(my_array[1])

1
2


In [14]:
my_array[0] = -1
print(my_array)

[-1  2  3  4  5]


In [15]:
my_new_array = np.zeros((5))
my_new_array

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
my_new_array1 = np.ones((5))
my_new_array1

array([ 1.,  1.,  1.,  1.,  1.])

In [18]:
my_random_array = np.random.random((5))      # 0到1的随机数
my_random_array

array([ 0.55307844,  0.30363362,  0.04684899,  0.30048787,  0.40919547])

In [19]:
# 创建二维数组

In [20]:
my_2d_array = np.zeros((2,3))
my_2d_array

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
my_2d_array_new = np.ones((2,4)) 
my_2d_array_new

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [22]:
my_array = np.array([[4,5],[6,1]])
my_array

array([[4, 5],
       [6, 1]])

In [23]:
my_array[0][1]

5

In [24]:
my_array.shape

(2, 2)

In [25]:
my_array_colunm_2 = my_array[:,1]   #取第二列
my_array_colunm_2

array([5, 1])

In [29]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
print('******')
summ = a + b    #逐个元素相加
diff = a - b    #逐个元素相减
product = a * b    #逐个元素相乘，而非矩阵乘法
quotient = a / b    #逐个元素相除
print(summ);print(diff);print(product);print(quotient)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
******
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [30]:
matrix_product = a.dot(b)
matrix_product

array([[19, 22],
       [43, 50]])

## NumPy简单入门教程

In [31]:
#1D Array

In [32]:
import numpy as np

In [33]:
a = np.array([0,1,2,3,4])
b = np.array((0,1,2,3,4))   #b与a一致
c = np.arange(5)    #与range()功能一样
d = np.linspace(0,2*np.pi,5)
print(a);print(b);print(c);print(d)
print(a[3])

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[ 0.          1.57079633  3.14159265  4.71238898  6.28318531]
3
